/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.liferayasif.person.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Person service. Represents a row in the &quot;FOO_Person&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>org.liferayasif.person.model.impl.PersonModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>org.liferayasif.person.model.impl.PersonImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Person
 * @generated
 */
@ProviderType
public interface PersonModel extends BaseModel<Person> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a person model instance should use the {@link Person} interface instead.
	 */

	/**
	 * Returns the primary key of this person.
	 *
	 * @return the primary key of this person
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this person.
	 *
	 * @param primaryKey the primary key of this person
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this person.
	 *
	 * @return the uuid of this person
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this person.
	 *
	 * @param uuid the uuid of this person
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the person ID of this person.
	 *
	 * @return the person ID of this person
	 */
	public long getPersonId();

	/**
	 * Sets the person ID of this person.
	 *
	 * @param personId the person ID of this person
	 */
	public void setPersonId(long personId);

	/**
	 * Returns the name of this person.
	 *
	 * @return the name of this person
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this person.
	 *
	 * @param name the name of this person
	 */
	public void setName(String name);

	/**
	 * Returns the age of this person.
	 *
	 * @return the age of this person
	 */
	public int getAge();

	/**
	 * Sets the age of this person.
	 *
	 * @param age the age of this person
	 */
	public void setAge(int age);

	/**
	 * Returns the gender of this person.
	 *
	 * @return the gender of this person
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this person.
	 *
	 * @param gender the gender of this person
	 */
	public void setGender(String gender);

	/**
	 * Returns the email ID of this person.
	 *
	 * @return the email ID of this person
	 */
	@AutoEscape
	public String getEmailId();

	/**
	 * Sets the email ID of this person.
	 *
	 * @param emailId the email ID of this person
	 */
	public void setEmailId(String emailId);

	/**
	 * Returns the nationality of this person.
	 *
	 * @return the nationality of this person
	 */
	@AutoEscape
	public String getNationality();

	/**
	 * Sets the nationality of this person.
	 *
	 * @param nationality the nationality of this person
	 */
	public void setNationality(String nationality);

	/**
	 * Returns the occupation of this person.
	 *
	 * @return the occupation of this person
	 */
	@AutoEscape
	public String getOccupation();

	/**
	 * Sets the occupation of this person.
	 *
	 * @param occupation the occupation of this person
	 */
	public void setOccupation(String occupation);

}