/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.liferayasif.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Student service. Represents a row in the &quot;School_Student&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>org.liferayasif.model.impl.StudentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>org.liferayasif.model.impl.StudentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Student
 * @generated
 */
@ProviderType
public interface StudentModel extends BaseModel<Student> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a student model instance should use the {@link Student} interface instead.
	 */

	/**
	 * Returns the primary key of this student.
	 *
	 * @return the primary key of this student
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this student.
	 *
	 * @param primaryKey the primary key of this student
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this student.
	 *
	 * @return the uuid of this student
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this student.
	 *
	 * @param uuid the uuid of this student
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the student ID of this student.
	 *
	 * @return the student ID of this student
	 */
	public long getStudentId();

	/**
	 * Sets the student ID of this student.
	 *
	 * @param studentId the student ID of this student
	 */
	public void setStudentId(long studentId);

	/**
	 * Returns the user name of this student.
	 *
	 * @return the user name of this student
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this student.
	 *
	 * @param userName the user name of this student
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this student.
	 *
	 * @return the create date of this student
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this student.
	 *
	 * @param createDate the create date of this student
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this student.
	 *
	 * @return the modified date of this student
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this student.
	 *
	 * @param modifiedDate the modified date of this student
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the father name of this student.
	 *
	 * @return the father name of this student
	 */
	@AutoEscape
	public String getFatherName();

	/**
	 * Sets the father name of this student.
	 *
	 * @param fatherName the father name of this student
	 */
	public void setFatherName(String fatherName);

	/**
	 * Returns the male of this student.
	 *
	 * @return the male of this student
	 */
	public boolean getMale();

	/**
	 * Returns <code>true</code> if this student is male.
	 *
	 * @return <code>true</code> if this student is male; <code>false</code> otherwise
	 */
	public boolean isMale();

	/**
	 * Sets whether this student is male.
	 *
	 * @param male the male of this student
	 */
	public void setMale(boolean male);

	/**
	 * Returns the address ID of this student.
	 *
	 * @return the address ID of this student
	 */
	public int getAddressId();

	/**
	 * Sets the address ID of this student.
	 *
	 * @param addressId the address ID of this student
	 */
	public void setAddressId(int addressId);

	/**
	 * Returns the dob of this student.
	 *
	 * @return the dob of this student
	 */
	public Date getDob();

	/**
	 * Sets the dob of this student.
	 *
	 * @param dob the dob of this student
	 */
	public void setDob(Date dob);

	/**
	 * Returns the email of this student.
	 *
	 * @return the email of this student
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this student.
	 *
	 * @param email the email of this student
	 */
	public void setEmail(String email);

}